global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'substations'
    static_configs:
      - targets: 
        - 'substation_1:8001'
        - 'substation_2:8001'
        - 'substation_3:8001'
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'load_balancer'
    static_configs:
      - targets: ['load_balancer:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'charge_request_service'
    static_configs:
      - targets: ['charge_request_service:8000']
    scrape_interval: 10s
    metrics_path: '/health'